apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  APP_ENV: "development"
  APP_NAME: "k8s-lab"
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
stringData:
  DB_PASSWORD: "supersecret123"
  API_KEY: "marius-k8s-lab-key"
